---
- name: Install Apache and its modules
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2
    - libapache2-mod-fastcgi

- name: Activate mod_rewrite
  apache2_module: 
    name: rewrite
    state: present

- name: Activate mod_fastcgi
  apache2_module: 
    name: fastcgi
    state: present

- name: Copy virtual host setup over
  template: 
    src: templates/vhost.conf
    dest: /etc/apache2/sites-available/

- name: Activate virtual host
  command: a2ensite vhost

- name: Deactivate default vhost
  command: a2dissite 000-default

- name: Ensure Apache is running
  service: 
    name: apache2 
    state: restarted 
    enabled: yes