---
- name: apt-get update hack
  shell: apt-get update

- name: Install utilities
  apt: name={{item}} state=latest
  ignore_errors: yes
  with_items:
    - git
    - unzip
    - python-pip
    - python-dev
    - build-essential

- name: Set timezone variables
  copy: content="{{ timezone }}"
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes

- name: Put "vagrant" user in www-data group
  user:
    name: "vagrant"
    groups: "www-data"
    append: yes

- name: Symlink web root to site
  file:
    src: "/vagrant/wordpress"
    dest: "/var/www/wordpress"
    state: "link"
    force: yes

  notify:
    - update timezone