---
- name: Install PHP and its modules
  apt: pkg={{ item }} state=latest
  with_items:
    - php7.1
    - php7.1-cli
    - php7.1-curl
    - php7.1-fpm
    - php7.1-mcrypt
    - php7.1-gd
    - php-imagick
    - php7.1-mysql
    - php7.1-xmlrpc
    - php7.1-xml