- name: Download WP-CLI
  get_url:
    url: "https://github.com/wp-cli/wp-cli/releases/download/v1.1.0/wp-cli-1.1.0.phar"
    dest: /tmp/wp-cli-1.1.0.phar

- name: Install WP-CLI
  command: rsync -c --chmod=0755 --info=name /tmp/wp-cli-1.1.0.phar /usr/bin/wp
  args:
    warn: false
  register: wp_cli
  changed_when: wp_cli.stdout == 'wp-cli-1.1.0.phar'
  
# Create /tmp/completion.bash here - it worked adding it manually

- name: Create /tmp/wp-completion-1.1.0.bash
  command: touch /tmp/wp-completion-1.1.0.bash
  args:
    creates: /tmp/wp-completion-1.1.0.bash
    warn: false

- name: Retrieve WP-CLI tab completions
  command: curl -4Ls "https://raw.githubusercontent.com/wp-cli/wp-cli/v1.1.0/utils/wp-completion.bash" -o /tmp/wp-completion-1.1.0.bash
  args:
    creates: /tmp/wp-completion-1.1.0.bash
    warn: false

- name: Install WP-CLI tab completions
  command: rsync -c --chmod=0644 --info=name /tmp/wp-completion-1.1.0.bash /etc/bash_completion.d/wp-completion.bash
  args:
    warn: false
  register: wp_cli_completion
  changed_when: wp_cli_completion.stdout == 'wp-completion-1.1.0.bash'